site_name: Chase's Blog
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.prune  #仅包含可见的导航
    - navigation.footer
    - toc.follow
    # - navigation.sections
    
    - search.suggest
    - search.highlight

    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    
    - header.autohide

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: cyan

plugins:
  - search
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tsai-shiyuan
    - icon: fontawesome/brands/pied-piper-alt
      link: https://www.cnblogs.com/chasetsai

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  

copyright: Copyright &copy; 2024 Chase Tsai
  


